### PR TITLE
Make my IDE Happy

### PR DESCRIPTION
**Pull request by forax**
Hi Charles,
I've fixed all the generics issues (mostly changing Class to Class<?>)
so now my IDE is happy :)

### CODE REVIEW

**Comment by headius** [comment]
What IDE are you using that demands `Class<?>`? The other changes seem fine, but that change in particular drives me a little nuts. It's as if any class that *can* be parameterized *must* be parameterized...

**Comment by forax** [comment]
Either Eclipse or IntelliJ Idea, javac with -Xlint:all.
Any class that can be parameterized must be parameterized otherwise the compiler will not insert the casts (and bridge methods) when required. For java.lang.Class, given that the class is covariant, it's not as awful as with say ArrayList because you can not change the constructor at runtime so the only thing you risk is to not fail early when you call newInstance() and fail later in the code.

**Comment by headius** [comment]
Well I'll be damned...I guess you're right. Why did we add generics again? :-D

**Comment by headius** [comment]
Wrong button!

**Comment by forax** [comment]
> Well I'll be damned...I guess you're right. Why did we add generics again? :-D
to close the mouth of academics saying that Java has no generics, no ?

**Comment by headius** [comment]
Hah, indeed :-)

**Pull request merged**
